[main]
# Fuentes e iconos
font=JetBrains Mono:size=12
icon-theme=Adwaita
fields=name,generic,comment,exec
terminal=foot
prompt="Buscar... "

# Dimensiones del menú
lines=10
width=35
horizontal-pad=20
vertical-pad=15
inner-pad=10

# Bordes redondeados idénticos a tus ventanas
radius=12

[colors]
# Los colores usan formato RRGGBBAA (los últimos dos números son la transparencia)
# background: Fondo oscuro con 85% de transparencia (d9)
background=1e1e2edd
# text: Texto blanco/azul claro
text=cdd6f4ff
# match: Color de las letras que coinciden al escribir
match=ff79c6ff
# selection: Fondo de la opción seleccionada
selection=bd93f9ff
# selection-text: Texto de la opción seleccionada 
selection-text=11111bff
# border: El borde de la ventana
border=ff79c6ff

[border]
width=2
radius=12
